inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# Allow PostHog global variable
Style/GlobalVars:
  AllowedVariables:
    - $posthog
