-
   name: Bamboo Pulp Straws
   sku: BB-PULP-15
   pac_size: 5000
   colour: Natural/Beige
   price: 75.00
   width_in_mm: 6
   height_in_mm: 150
-
   name: Bamboo Pulp Straws
   sku: BB-PULP-20
   pac_size: 5000
   colour: Natural/Beige
   price: 80.00
   width_in_mm: 6
   height_in_mm: 200
-
   name: Bamboo Pulp Straws
   sku: BB-PULP-JUM
   pac_size: 5000
   colour: Natural/Beige
   price: 108.30
   width_in_mm: 8
   height_in_mm: 200
-
   name: Bamboo Pulp Straws
   sku: BB-PULP-10M
   pac_size: 3600
   colour: Natural/Beige
   price: 134.00
   width_in_mm: 10
   height_in_mm: 200

-
   name: Bamboo Boba Pulp Straws - Wrapped
   sku: BB-PULP-BOB
   pac_size: 2400
   colour: Natural/Beige
   price: 114.40
   width_in_mm: 12
   height_in_mm: 210
-
   name: Bamboo Fibre Straws
   sku: BB-FBRBL-15
   pac_size: 2500
   colour: Black
   price: 56.40
   width_in_mm: 6
   height_in_mm: 150
-
   name: Bamboo Fibre Straws
   sku: BB-FBRBL-20
   pac_size: 2500
   colour: Black
   price: 65.80
   width_in_mm: 6
   height_in_mm: 200
-
   name: Bamboo Fibre Straws
   sku: BB-FBRN-15
   pac_size: 2500
   colour: Natural/Beige
   price: 56.40
   width_in_mm: 6
   height_in_mm: 150
-
   name: Bamboo Fibre Straws
   sku: BB-FBRN-20
   pac_size: 2500
   colour: Natural/Beige
   price: 65.80
   width_in_mm: 6
   height_in_mm: 200
-
   name: Agave Straws
   sku: PK-BOX-15
   pac_size: 2500
   colour: Natural/Brown
   price: 57.5
   width_in_mm: 6
   height_in_mm: 150
-
   name: Agave Straws
   sku: PK-BOX-21
   pac_size: 2500
   colour: Natural/Brown
   price: 68.5
   width_in_mm: 6
   height_in_mm: 210
-
   name: Agave Straws
   sku: PK-JUM-21
   pac_size: 2500
   colour: Natural/Brown
   price: 76.3
   width_in_mm: 8
   height_in_mm: 210

